/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package mx.dns.findreplacer

class App {

    static void main(String[] args) {
      
        def testFilePath = App.class.getClassLoader().getResource("test.txt").getFile()
        FindReplacer.findReplace(testFilePath, "debe ser", "worked!!!")
    }
}
